# Generated by Django 5.2.5 on 2025-11-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categoria_stug_post_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, default='posts/default.jpg', null=True, upload_to='blog/'),
        ),
    ]
