"""
Django settings for portafolio_app project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from   dotenv import load_dotenv
import dj_database_url



load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u3a-n$-=aobz-t1#vsse8w+wop0e56wzw-zyr23w$d74_e5!m*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG')







#'.ngrok-free.app'
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".railway.app",
    '.ngrok-free.app'
]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'blog',
    'usuario',
    'portafolio',
    'django_ckeditor_5',

]


CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_5_CUSTOM_CSS = 'static/css/custom_ckeditor.css'  # opcional



CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': {
            'items': ['heading', '|', 'bold', 'italic', 'link',
                      'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],
                    }

    },

}


if DEBUG in ['True' , True]:
    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'whitenoise.middleware.WhiteNoiseMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
#        "django_browser_reload.middleware.BrowserReloadMiddleware",        
]
else:    
    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'whitenoise.middleware.WhiteNoiseMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        
]
        
    
    

ROOT_URLCONF = 'portafolio_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR , 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portafolio_app.wsgi.application'
AUTH_USER_MODEL =  'usuario.CustomUser'
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


if DEBUG in ['True' , True]:
    DATABASES = {
      'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
 }
}
else:
    DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=True
    )
}

    # DATABASES = {
    #         'default': {   
    #         'ENGINE': 'django.db.backends.postgresql',
    #         'NAME': os.getenv('DB_NAME'),
    #         'USER': os.getenv("DB_USER"),
    #         'PASSWORD': os.getenv("DB_PASSWORD"),
    #         'HOST': os.getenv("DB_HOST"),
    #         'PORT': os.getenv("DB_PORT"),

    #     }
    # }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#solo para  compartir mi pagina a otra persona
CSRF_TRUSTED_ORIGINS = [
        "https://*.ngrok-free.app"
        
        "https://*.railway.app",


]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "static"),

]



STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


ADMIN_SITE_HEADER = "Panel de Administración - Portafolio JX"
ADMIN_SITE_TITLE = "Portafolio JX"
ADMIN_INDEX_TITLE = "Bienvenido al panel"





# Looking to send emails in production? Check out our Email API/SMTP product!
#EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
#EMAIL_HOST_USER = 'd66b3621a199de'
#EMAIL_HOST_PASSWORD = '6badcb82a8848e'
#EMAIL_PORT = '2525'


# esto es para enviar correos
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')        # tu Gmail
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")  # contraseña de aplicación
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER





EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"   # backend de django-sendgrid-v5
SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")       # tu clave SG.xxxxx
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

#this  es para recarga aauutomatica de cambios
#pip install django-browser-reload
